islandora_collection_search.settings:
  type: config_object
  label: Settings
  mapping:
    islandora_collection_search_ancestor_field:
      type: string
    islandora_collection_search_all_pages:
      type: boolean
    islandora_collection_search_display_label:
      type: boolean
    islandora_collection_search_advanced_search_alter:
      type: boolean
    islandora_collection_search_retain_search_values:
      type: boolean
    islandora_collection_search_searchable_collections:
      type: sequence
      sequence:
        type: string
